apiVersion: v1
kind: Service
metadata:
  name: hello-arc
  namespace: hello-arc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-arc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-arc
  namespace: hello-arc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-arc
  template:
    metadata:
      labels:
        app: hello-arc
    spec:
      containers:
      - name: hello-arc
        image: azurearcjumpstart.azurecr.io/hello-arc-gitops:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Replica 1 change Hi Mark 1:1 - Welcome to Azure Arc GitOps Demo!
